### PR TITLE
move texture on conveyor belt mesh

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
* add functionality to move texture on conveyor belt mesh (using _speed_ parameter)
* add mesh and textures to ROS2 assets
* fix typos

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
It was tested using the empty level with the following setup:
image

**Comment by jhanca-robotecai** [comment]
PR updated to the newest conveyor belt model, tested with level `robotic_test` of [o3de-physics-test-scene](https://github.com/o3de/o3de-physics-test-scene) `robotic_arm_template` commit ec99bd4c2759f997a5cae2a9c7bf2b370d69df80

in which conveyor belt physics component needs to be connected with the mesh+material component:
image

**Comment by jhanca-robotecai** [comment]
Added another commit with material selector for the physics.

**Comment by jhanca-robotecai** [comment]
Another commit with texture scaling added (it allows to change the speed of the texture movement if the mesh/texture size is different than 1 meter)

image

**Comment by michalpelka** [comment]
looks ok, please keep this PR only with code, no assets.

**Comment by jhanca-robotecai** [comment]
> looks ok, please keep this PR only with code, no assets.

I removed the assets

**Pull request merged**
